# Generated by Django 4.2.3 on 2023-07-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weatherforecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=60)),
                ('lon', models.CharField(max_length=60)),
            ],
        ),
    ]
