# Generated by Django 4.2.3 on 2023-07-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='lat',
            field=models.FloatField(max_length=60),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='lon',
            field=models.FloatField(max_length=60),
        ),
    ]
